
function print1()
{
    var a = window.open('', '', 'height=500, width=500');
        a.document.write('<!DOCTYPE html>');
        a.document.write('<html lang="en">');
        a.document.write('<head>');
        a.document.write('<meta charset="utf-8">');
        a.document.write('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/paper-css/0.3.0/paper.css">');
        a.document.write('<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">');
        a.document.write('<style type="text/css">');
        a.document.write('@page { size: A4 }');
        a.document.write('.sub-header{');
        a.document.write('margin: 10px 0 10px 0;');
        a.document.write('border-bottom: 0px solid #eee;');
        a.document.write('}');
        a.document.write('.column1, column2{');
        a.document.write('width: 100%;');
        a.document.write('}');
        a.document.write('.tf{');
        a.document.write('margin: 10px 0 10px 0;');
        a.document.write('</style>');
        a.document.write('</head>');
        a.document.write('<body class="A4">');
        a.document.write('<section class="sheet padding-10mm" style="margin: 0 auto;">');
        a.document.write('<div _id="head" class="row">');
        a.document.write('<h5 align="center"><b>Financial Freedom Plans Inc.</b></h5>');
        a.document.write('<p align="center"><i>"We need more people like you to serve others lives"</i></p>');
        a.document.write('<div class="col" style="text-align: right;">');
        a.document.write('<img src="" style="width: 150px; height: 150px;" class="img-rounded">');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('<div class="sub-header"><h4><b>Members Information</b></h4>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Date of Application: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Member ID: </div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Contract No.: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Full Name: </b></div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Age: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Address: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Birthday: </div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Birthplace: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Gender: </div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Civil Status: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Height: </div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Weight: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="phi" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Contact No.: </div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Email Address: </div>');
        a.document.write('</div>');
        a.document.write('<div class="sub-header"><h4><b>Beneficiaries</b></h4></div>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><i><b>Primary</b></i></div>');
        a.document.write('</div>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Name: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Relationship: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Birthday: </div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Age: </div>');
        a.document.write('</div>');
        a.document.write('<br>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><i><b>Contingent</b></i></div>');
        a.document.write('</div>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Name: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Relationship: </div>');
        a.document.write('</div>');
        a.document.write('<div _id="bnfs" class="row" >');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Birthday: </div>');
        a.document.write('<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">Age: </div>');
        a.document.write('</div>');
        a.document.write('<div class="sub-header"><h4><b>Plan Type</b></h4></div>');
        a.document.write('<div _id="pt" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Plan Type: </div>');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Months To Pay:</div>');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Total Amount:</div>');
        a.document.write('</div>');
        a.document.write('<div _id="pt" class="row">');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Mode of Payment: </div>');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">No. of Months Paid:</div>');
        a.document.write('<div class="col-lg-4 col-md-4 col-sm-4 col-xs-4">Remaining:</div>');
        a.document.write('</div>');
        a.document.write('<div class="sub-header"><h4><b>Health Declaration</b></h4></div>');
        a.document.write('<div> I hereby declare that I am FREE from any harmful and dreaded diseases list down below<i>(Answer with Yes or No)</i><br><i>The following, among others, when occurring during the first year of coverage after effective date are considered Pre-Existing.</i></div><br>');
        a.document.write('<div class="row">');
        a.document.write('<div _id="column1" class="column1">');
        a.document.write('<div class="form-row col-lg-6 col-md-6 col-sm-6 col-xs-6">');
        a.document.write('<div class="form-row">1. Any Cardiovascular Problem. <b>NO</b></div>');
        a.document.write('<div class="form-row">2. Cancer/Tumor/Neoplasm. <b>NO</b></div>');
        a.document.write('<div class="form-row">3. Diabetes Mellitus <i>(all types)</i>. <b>NO</b></div>');
        a.document.write('<div class="form-row">4. Kidney Problem. <b>NO</b></div>');
        a.document.write('<div class="form-row">5. Severe Respiratory Problem. <b>NO</b></div>');
        a.document.write('<div class="form-row">6. Hernias. <b>NO</b></label>');
        a.document.write('<div class="form-row">7. Endometriosis. <b>NO</b></div>');
        a.document.write('<div class="form-row">8. Hemorrhoids. <b>NO</b></div>');
        a.document.write('<div class="form-row">9. Ear-Nose-Throat Condition Requiring Surgery. <b>NO</b></div>');
        a.document.write('<div class="form-row">10. Cataracts/Glaucoma. <b>NO</b></div>');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('<div class="row">');
        a.document.write('<div _id="column2" class="column2">');
        a.document.write('<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">');
        a.document.write('<div class="form-row">11. Epilepsy. <b>NO</b></div>');
        a.document.write('<div class="form-row">12. Cirrhosis of the Liver. <b>NO</b></div>');
        a.document.write('<div class="form-row">13. Anal Fistulae. <b>NO</b></div>');
        a.document.write('<div class="form-row">14. Calculi of the Urinary System. <b>NO</b><div>');
        a.document.write('<div class="form-row">15. Gastric/Duodenal Ulcer. <b>NO</b></div>');
        a.document.write('<div class="form-row">16. Hallux Valgus. <b>NO</b></div>');
        a.document.write('<div class="form-row">17. Collagen Diseases. <b>NO</b></div>');
        a.document.write('<div class="form-row">18. Hypertension. <b>NO</b></div>');
        a.document.write('<div class="form-row">19. Cholecystitis/Choielithiasis. <b>NO</b></div>');
        a.document.write('<div class="form-row">20. Others. <b>N/A</b></div>');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('</div>');
        a.document.write('</section>');
        a.document.write('</body>');
        a.document.write('</html>');
        a.document.close();
        a.print();
}